#!/bin/bash
if [ -n "$WS_DEBUG" ]; then
    /bin/bash
else
    LOG_DIR="/home/student/.local/state/workspace-logs/"
    mkdir -p "$LOG_DIR"
    asciinema rec "$LOG_DIR/$(date '+%Y-%m-%d_%H-%M-%S.%3N').cast" -q -c "/bin/bash"
fi
