name: Workspace Image Release

on:
  release:
    types: [published]

env:
  IMAGE_NAME: cse30

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      - name: Build Docker Image
        run: |
          REPO_NAME=${{ secrets.DOCKER_USERNAME }}/${{ env.IMAGE_NAME }}
          IMAGE_VERSION=${{ github.event.release.tag_name }}
          docker buildx build --platform linux/amd64 \
                              --tag $REPO_NAME:$IMAGE_VERSION \
                              --tag $REPO_NAME:latest \
                              --push .
